// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeakPals_Project.Models;

#nullable disable

namespace PeakPals_Project.Migrations
{
    [DbContext(typeof(PeakPalsContext))]
    partial class PeakPalsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PeakPals_Project.Models.ClimbAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("ClimbId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ClimberID")
                        .HasColumnType("int")
                        .HasColumnName("ClimberID");

                    b.Property<int?>("ClimberId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("SuggestedGrade")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.HasIndex("ClimberID");

                    b.HasIndex("ClimberId");

                    b.ToTable("ClimbAttempt");
                });

            modelBuilder.Entity("PeakPals_Project.Models.Climber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("AspnetIdentityId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ASPNetIdentityId");

                    b.Property<string>("Bio")
                        .HasMaxLength(1600)
                        .HasColumnType("nvarchar(1600)");

                    b.Property<string>("City")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CustomLink")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImageLink")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LinkText")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("State")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Climber__3214EC27495224C8");

                    b.ToTable("Climber");
                });

            modelBuilder.Entity("PeakPals_Project.Models.FitnessDataEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("BodyWeight")
                        .HasColumnType("int");

                    b.Property<int?>("ClimberId")
                        .HasColumnType("int")
                        .HasColumnName("ClimberID");

                    b.Property<string>("ClimbingExperience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClimbingGrade")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Result")
                        .HasColumnType("int");

                    b.Property<int?>("TestId")
                        .HasColumnType("int")
                        .HasColumnName("TestID");

                    b.HasKey("Id")
                        .HasName("PK__FitnessD__3214EC27A69CA072");

                    b.HasIndex("ClimberId");

                    b.HasIndex("TestId");

                    b.ToTable("FitnessDataEntry");
                });

            modelBuilder.Entity("PeakPals_Project.Models.FitnessTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__FitnessT__3214EC27C00405FE");

                    b.ToTable("FitnessTest");
                });

            modelBuilder.Entity("PeakPals_Project.Models.ClimbAttempt", b =>
                {
                    b.HasOne("PeakPals_Project.Models.Climber", null)
                        .WithMany()
                        .HasForeignKey("ClimberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeakPals_Project.Models.Climber", "Climber")
                        .WithMany("ClimbAttempts")
                        .HasForeignKey("ClimberId");

                    b.Navigation("Climber");
                });

            modelBuilder.Entity("PeakPals_Project.Models.FitnessDataEntry", b =>
                {
                    b.HasOne("PeakPals_Project.Models.Climber", "Climber")
                        .WithMany("FitnessDataEntries")
                        .HasForeignKey("ClimberId")
                        .HasConstraintName("FK_FitnessDataEntry_Climber_ID");

                    b.HasOne("PeakPals_Project.Models.FitnessTest", "Test")
                        .WithMany("FitnessDataEntries")
                        .HasForeignKey("TestId")
                        .HasConstraintName("FK_FitnessDataEntry_Test_ID");

                    b.Navigation("Climber");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("PeakPals_Project.Models.Climber", b =>
                {
                    b.Navigation("ClimbAttempts");

                    b.Navigation("FitnessDataEntries");
                });

            modelBuilder.Entity("PeakPals_Project.Models.FitnessTest", b =>
                {
                    b.Navigation("FitnessDataEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
